### ISSUE TITLE
Install on Raspberry Pi 2 Arch Linux

### ISSUE THREAD

**Issue by hansheijmans** [xemle/spop-web#2]
How do I install on Raspberry Pi 2 with Arch Linux. I get the message:
"libicui18n.so.57: cannot open shared object file"
Which dependencies are needed?
Install with Docker also fails. Docker assumes Debian (-like) distro is installed.

**Comment by hansheijmans** [comment]
Installation on Fedora also fails. When connecting to localhost:3000 all I get is:
"Cannot GET /" and the rest of the screen is blank.

**Comment by xemle** [comment]
Which steps have you done regarding the installation instruction of the README.md and where are these failing? Could you describe how you installed spop-web step by step, so I can reproduce your error.

**Comment by hansheijmans** [comment]
Hi xemle,

Thanks for your reply!

I tried to install spop-web on a RPi2 with RuneAudio 0.4 installed. I know the RuneAudio team is not using the latest Archlinux updates so I will perform a fresh and clean install of Archlinux and spop with the latest updates first. Then I will try to install spop-web and let you know if there are any error messages.

Greetz,
Hans.

**Comment by hansheijmans** [comment]
Hi xemle,

Did a fresh install of ArchlinuxArm. Compiled spop until working and controlled using telnet.

I followed your list of commands to install, this is what I got:

Output of "npm install -g bower gulp-cli" showed no errors.
Output of "npm install" showed the following warnings:

npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

bower install needed "--allow-root" option as I am only using root account on my RPi2, no errors

Output of "gulp" command:

[root@rpi2arch spop-web]# gulp
(node:826) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[12:22:51] Using gulpfile ~/spop-web/gulpfile.js
[12:22:51] Starting 'less'...
[12:22:51] Starting 'ng-templates'...
[12:22:52] Starting 'copyFontsFromBower'...
[12:22:55] Finished 'copyFontsFromBower' after 3.14 s
[12:22:55] Starting 'copyDist'...
[12:22:56] Finished 'copyDist' after 763 ms
[12:23:03] Finished 'less' after 12 s
[12:23:03] Finished 'ng-templates' after 12 s
[12:23:03] Starting 'html'...
(node:826) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[12:23:04] gulp-inject 1 files into index.html.

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: styles/app.css: error: couldn't process source due to parse error
Unexpected token (2:5)

So unfortunately some errors and warnings. Maybe some dependencies are not met.
Can you help me solve this?

Thanks and regards,
Hans.

**Comment by xemle** [comment]
Mm. I was trying to build it on my desktop pc - it it went through without problems. I am using node 5.5.0 and npm 3.3.12. Alternativly, you can compile spop-web on your desktop pc and copy the final files to the rasperry pi. These files are:
- dist/*
- lib/*
- node_modules/*
- index.js

Than you can start the spop-web with

```
$ node index.js
```

**Comment by hansheijmans** [comment]
I managed to get it compiled and working on my laptop running Fedora 23 (with all updates installed) and use it to remotely control spop on my Rpi2 using:

$ node index.js --spop-host <my RPi2 IP-address>:3000

To get it compiled I had to run the npm-commands as root (using sudo) and the bower and gulp commands as a myself.

Fedora: node --version --> v0.10.42, npm -v --> 1.3.6
RPi2, archlinuxarm: node --version --> v6.2.2, npm -v --> 3.9.6

Still I would like to have it running on the Pi itself but that fails, see my previous comments. Maybe you could give me some directions how to cross-compile spop-web for ARMv7 on Fedora? I don't get anywhere with Google. Nicest thing would be to compile on my Pi which is running the latest Archlinuxarm (https://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2) but I guess there are some wrong versions of libraries or missing dependencies.

Anyway, I must say the interface looks really nice and useful, both on my pc and Android device!

**Comment by hansheijmans** [comment]
IT WORKS!!

Just by downgrading node and npm using Node Version Manager:

https://github.com/creationix/nvm

And downgraded to version 4.4.6 (LTS) which nvm downloads from nodejs.org (armv7 binaries).
All compile commands ended without any errors!

Compile output:

[root@rpi2arch spop-web]# npm install -g bower gulp-cli
/root/.nvm/versions/node/v4.4.6/bin/gulp -> /root/.nvm/versions/node/v4.4.6/lib/node_modules/gulp-cli/bin/gulp.js
/root/.nvm/versions/node/v4.4.6/bin/bower -> /root/.nvm/versions/node/v4.4.6/lib/node_modules/bower/bin/bower
gulp-cli@1.2.1 /root/.nvm/versions/node/v4.4.6/lib/node_modules/gulp-cli
├── mute-stdout@1.0.0
├── interpret@1.0.1
├── pretty-hrtime@1.0.2
├── archy@1.0.0
├── fancy-log@1.2.0 (time-stamp@1.0.1)
├── tildify@1.2.0 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── gulplog@1.0.0 (glogg@1.0.0)
├── wreck@6.3.0 (boom@2.10.1, hoek@2.16.3)
├── semver-greatest-satisfied-range@1.0.0 (semver-regex@1.0.0, semver@4.3.6)
├── lodash.sortby@4.5.0 (lodash._baseeach@4.1.3, lodash.rest@4.0.3, lodash._baseflatten@4.2.1, lodash._baseiteratee@4.7.0)
├── yargs@3.32.0 (decamelize@1.2.0, camelcase@2.1.1, y18n@3.2.1, window-size@0.1.4, os-locale@1.4.0, cliui@3.2.0, string-width@1.0.1)
├── liftoff@2.2.4 (rechoir@0.6.2, extend@3.0.0, flagged-respawn@0.3.2, findup-sync@0.3.0, resolve@1.1.7)
└── matchdep@1.0.1 (stack-trace@0.0.9, findup-sync@0.3.0, resolve@1.1.7, micromatch@2.3.10)

bower@1.7.9 /root/.nvm/versions/node/v4.4.6/lib/node_modules/bower
[root@rpi2arch spop-web]# npm install
[root@rpi2arch spop-web]# bower install --allow-root
[root@rpi2arch spop-web]# gulp
[11:38:46] Using gulpfile ~/spop-web/gulpfile.js
[11:38:46] Starting 'less'...
[11:38:46] Starting 'ng-templates'...
[11:38:46] Starting 'copyFontsFromBower'...
[11:38:55] Finished 'less' after 9.46 s
[11:38:55] Finished 'copyFontsFromBower' after 9.34 s
[11:38:55] Starting 'copyDist'...
[11:38:56] Finished 'ng-templates' after 9.65 s
[11:38:56] Starting 'html'...
[11:38:57] gulp-inject 1 files into index.html.
[11:39:03] Finished 'copyDist' after 7.05 s
[11:39:48] Finished 'html' after 52 s
[11:39:48] Starting 'dist'...
[11:39:48] Finished 'dist' after 186 μs
[11:39:48] Starting 'default'...
[11:39:48] Finished 'default' after 99 μs

"Evidence" attached to this comment.
![2016-06-25 09 58 00](https://cloud.githubusercontent.com/assets/14160232/16356072/3dba1428-3acc-11e6-8274-29e5e00d8410.png)

**Comment by hansheijmans** [comment]
Thanks for this great piece of software!

**Comment by xemle** [comment]
Cool! I am happy that you found a way. But the way is strange with downgrading node.

Anyway. I will close this issue. Have fun with spop-web!
